"""Core modules for OpenClaw"""

from .config import VisionConfig, VisionMode, ConfigManager, ConfigValidationError
from .vision import (
    VisionEngine,
    ScreenCapture,
    OCREngine,
    FuzzyMatcher,
    TemplateMatcher,
    ColorDetector,
    ChangeDetector,
    RegressionDetector
)
from .actions import (
    RetryConfig,
    RetryStrategy,
    ActionExecutor,
    KeyboardAction,
    MouseAction,
    ActionSequence,
    TriggerAction
)
from .logger import Logger, get_logger, setup_logging
from .scheduler import Scheduler, ScheduleType, ScheduleJob, get_scheduler
from .workflow import WorkflowManager, Workflow, NodeType, WorkflowExecutor
from .window import WindowMonitor, WindowAction, start_window_monitor, stop_window_monitor, get_window_monitor
from .voice import VoiceEngine, VoiceTrigger, VoiceConfig, VoiceCommand, VoiceBackend, create_voice_trigger
from .ai import NLInterface, NLPParser, NLPConfig, AutomationIntent, NLPMode, create_nlp_interface
from .hot_reload import HotReloader, ConfigReloader, ReloadEvent, ReloadType, create_reloader
from .anomaly import (
    AnomalyDetector,
    Anomaly,
    AnomalyType,
    TriggerEvent,
    StatisticalAnalyzer,
    MovingAverageDetector,
    PatternDetector,
    get_anomaly_detector
)
from .automation import (
    Platform,
    AutomationBackend,
    LinuxAutomationBackend,
    WindowsAutomationBackend,
    MacOSAutomationBackend,
    get_platform,
    create_automation_backend,
    get_automation_backend,
    press,
    type_text,
    click,
    move_to,
    get_screen_size,
    get_cursor_position,
    Point,
    Key
)
from .blip import (
    BLIPEngine,
    BLIPModelType,
    CaptionResult,
    VQAResult,
    MiniMaxAI,
    get_blip_engine,
    get_minimax_ai,
    analyze_screen_with_blip,
    caption_screen,
    ask_screen
)
from .workspace import (
    EnvironmentType,
    WorkspaceConfig,
    WorkspaceManager,
    get_workspace_manager,
    get_current_workspace,
    switch_workspace,
    is_development,
    is_staging,
    is_production
)

__all__ = [
    "VisionConfig",
    "VisionMode",
    "ConfigManager",
    "ConfigValidationError",
    "VisionEngine",
    "ScreenCapture",
    "OCREngine",
    "FuzzyMatcher",
    "TemplateMatcher",
    "ColorDetector",
    "ChangeDetector",
    "RegressionDetector",
    "RetryConfig",
    "RetryStrategy",
    "ActionExecutor",
    "KeyboardAction",
    "MouseAction",
    "ActionSequence",
    "TriggerAction",
    "Logger",
    "get_logger",
    "setup_logging",
    "Scheduler",
    "ScheduleType",
    "ScheduleJob",
    "get_scheduler",
    "WorkflowManager",
    "Workflow",
    "NodeType",
    "WorkflowExecutor",
    "WindowMonitor",
    "WindowAction",
    "start_window_monitor",
    "stop_window_monitor",
    "get_window_monitor",
    "VoiceEngine",
    "VoiceTrigger",
    "VoiceConfig",
    "VoiceCommand",
    "VoiceBackend",
    "create_voice_trigger",
    "NLInterface",
    "NLPParser",
    "NLPConfig",
    "AutomationIntent",
    "NLPMode",
    "create_nlp_interface",
    "HotReloader",
    "ConfigReloader",
    "ReloadEvent",
    "ReloadType",
    "create_reloader",
    "AnomalyDetector",
    "Anomaly",
    "AnomalyType",
    "TriggerEvent",
    "StatisticalAnalyzer",
    "MovingAverageDetector",
    "PatternDetector",
    "get_anomaly_detector",
    "Platform",
    "AutomationBackend",
    "LinuxAutomationBackend",
    "WindowsAutomationBackend",
    "MacOSAutomationBackend",
    "get_platform",
    "create_automation_backend",
    "get_automation_backend",
    "press",
    "type_text",
    "click",
    "move_to",
    "get_screen_size",
    "get_cursor_position",
    "Point",
    "Key",
    "BLIPEngine",
    "BLIPModelType",
    "CaptionResult",
    "VQAResult",
    "MiniMaxAI",
    "get_blip_engine",
    "get_minimax_ai",
    "analyze_screen_with_blip",
    "caption_screen",
    "ask_screen",
    "EnvironmentType",
    "WorkspaceConfig",
    "WorkspaceManager",
    "get_workspace_manager",
    "get_current_workspace",
    "switch_workspace",
    "is_development",
    "is_staging",
    "is_production",
]
